databases:
  - name: ajaxapp_production_db
    databaseName: ajaxapp_production_db
    user: ajaxapp_production_user
    region: ohio
    plan: free

services:
  - type: web
    name: ajaxapp_production
    env: python
    region: ohio
    plan: free
    branch: main
    healthCheckPath: /
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker"
    # startCommand: "gunicorn report_project.wsgi --log-file -"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ajaxapp_production_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

    autoDeploy: true